before_install:
  - gem sources --add https://rubygems.org/
  - gem install bundler -v 2.2.9

os:
  - linux
  - osx

dist:      bionic
osx_image: xcode12.2

language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7

script: 'bundle exec rake'