before_install:
  - gem install bundler

os:
  - linux
  - osx

dist:      bionic
osx_image: xcode12.5

language: ruby

rvm:
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0

script: 'bundle exec rake'